import { DocKey, getDocMetadata as getDocMetadataCore } from "@smart-doc/docs";
import { localeRecord, t, type Dictionary } from "intlayer";

const getDocMetadata = (doc: DocKey) =>
  t(localeRecord(async ({ locale }) => await getDocMetadataCore(doc, locale)));

const docDataContent: any = {
  key: "doc-data",
  content: {
    astroCourses: {
      title: t({
        en: "Astro Courses",
        fr: "Cours Astro",
        es: "Cursos Astro",
        de: "Astro-Kurse",
        it: "Corsi Astro",
        ja: "Astro コース",
        ko: "Astro 과정",
        zh: "Astro 课程",
        pt: "Cursos Astro",
        pl: "Kursy Astro",
        hi: "Astro कोर्स",
        ar: "دورات Astro",
        ru: "Курсы Astro",
      }),
      default: getDocMetadata("./docs/en/astro-courses.mdx"),
    },
    layouts: {
      title: t({
        en: "Layouts",
        fr: "Mises en page",
        es: "Diseños",
        de: "Layouts",
        it: "Layouts",
        ja: "レイアウト",
        ko: "레이아웃",
        zh: "布局",
        pt: "Layouts",
        pl: "Układy",
        hi: "लेआउट",
        ar: "التخطيط",
        ru: "Макеты",
      }),
      default: getDocMetadata("./docs/en/basics/layouts.mdx"),
    },
    editorSetup: {
      title: t({
        en: "Editor Setup",
        fr: "Configuration de l'éditeur",
        es: "Configuración del editor",
        de: "Editor-Setup",
        it: "Configurazione dell'editor",
        ja: "エディターの設定",
        ko: "에디터 설정",
        zh: "编辑器设置",
        pt: "Configuração do editor",
        pl: "Konfiguracja edytora",
        hi: "एडिटर सेटअप",
        ar: "إعداد المحرر",
        ru: "Настройка редактора",
      }),
      default: getDocMetadata("./docs/en/editor-setup.mdx"),
    },
    gettingStarted: {
      title: t({
        en: "Getting Started",
        fr: "Commencer",
        es: "Empezando",
        de: "Erste Schritte",
        it: "Iniziare",
        ja: "はじめに",
        ko: "시작하기",
        zh: "开始使用",
        pt: "Começando",
        pl: "Pierwsze kroki",
        hi: "शुरुआत करना",
        ar: "البدء",
        ru: "Начало работы",
      }),
      default: getDocMetadata("./docs/en/getting-started.mdx"),
    },
    installAndSetup: {
      title: t({
        en: "Install and Setup",
        fr: "Installation et configuration",
        es: "Instalación y configuración",
        de: "Installation und Einrichtung",
        it: "Installazione e configurazione",
        ja: "インストールとセットアップ",
        ko: "설치 및 설정",
        zh: "安装和设置",
        pt: "Instalação e configuração",
        pl: "Instalacja i konfiguracja",
        hi: "इंस्टॉल और सेटअप",
        ar: "التثبيت والإعداد",
        ru: "Установка и настройка",
      }),
      default: getDocMetadata("./docs/en/install-and-setup.mdx"),
    },
    developAndBuild: {
      title: t({
        en: "Develop and Build",
        fr: "Développer et construire",
        es: "Desarrollar y construir",
        de: "Entwickeln und erstellen",
        it: "Sviluppare e costruire",
        ja: "開発とビルド",
        ko: "개발 및 빌드",
        zh: "开发和构建",
        pt: "Desenvolver e construir",
        pl: "Programowanie i budowanie",
        hi: "विकसित करना और निर्माण",
        ar: "التطوير والبناء",
        ru: "Разработка и сборка",
      }),
      default: getDocMetadata("./docs/en/develop-and-build.mdx"),
    },
    contribute: {
      title: t({
        en: "Contribute",
        fr: "Contribuer",
        es: "Contribuir",
        de: "Beitragen",
        it: "Contribuire",
        ja: "貢献する",
        ko: "기여하기",
        zh: "贡献",
        pt: "Contribuir",
        pl: "Wkład",
        hi: "योगदान करना",
        ar: "المساهمة",
        ru: "Внести вклад",
      }),
      default: getDocMetadata("./docs/en/contribute.mdx"),
    },
    upgradeAstro: {
      title: t({
        en: "Upgrade Astro",
        fr: "Mettre à niveau Astro",
        es: "Actualizar Astro",
        de: "Astro aktualisieren",
        it: "Aggiornare Astro",
        ja: "Astro をアップグレード",
        ko: "Astro 업그레이드",
        zh: "升级 Astro",
        pt: "Atualizar Astro",
        pl: "Aktualizacja Astro",
        hi: "Astro अपग्रेड करें",
        ar: "ترقية Astro",
        ru: "Обновление Astro",
      }),
      default: getDocMetadata("./docs/en/upgrade-astro.mdx"),
    },
    // Basics
    astroComponents: {
      title: t({
        en: "Astro Components",
        fr: "Composants Astro",
        es: "Componentes Astro",
        de: "Astro-Komponenten",
        it: "Componenti Astro",
        ja: "Astro コンポーネント",
        ko: "Astro 컴포넌트",
        zh: "Astro 组件",
        pt: "Componentes Astro",
        pl: "Komponenty Astro",
        hi: "Astro घटक",
        ar: "مكونات Astro",
        ru: "Компоненты Astro",
      }),
      default: getDocMetadata("./docs/en/basics/astro-components.mdx"),
    },
    astroPages: {
      title: t({
        en: "Astro Pages",
        fr: "Pages Astro",
        es: "Páginas Astro",
        de: "Astro-Seiten",
        it: "Pagine Astro",
        ja: "Astro ページ",
        ko: "Astro 페이지",
        zh: "Astro 页面",
        pt: "Páginas Astro",
        pl: "Strony Astro",
        hi: "Astro पृष्ठ",
        ar: "صفحات Astro",
        ru: "Страницы Astro",
      }),
      default: getDocMetadata("./docs/en/basics/astro-pages.mdx"),
    },
    projectStructure: {
      title: t({
        en: "Project Structure",
        fr: "Structure du projet",
        es: "Estructura del proyecto",
        de: "Projektstruktur",
        it: "Struttura del progetto",
        ja: "プロジェクト構造",
        ko: "프로젝트 구조",
        zh: "项目结构",
        pt: "Estrutura do projeto",
        pl: "Struktura projektu",
        hi: "परियोजना संरचना",
        ar: "هيكل المشروع",
        ru: "Структура проекта",
      }),
      default: getDocMetadata("./docs/en/basics/project-structure.mdx"),
    },
    // Concepts
    islands: {
      title: t({
        en: "Islands",
        fr: "Îles",
        es: "Islas",
        de: "Inseln",
        it: "Isole",
        ja: "アイランド",
        ko: "아일랜드",
        zh: "岛屿",
        pt: "Ilhas",
        pl: "Wyspy",
        hi: "द्वीप",
        ar: "الجزر",
        ru: "Острова",
      }),
      default: getDocMetadata("./docs/en/concepts/islands.mdx"),
    },
    whyAstro: {
      title: t({
        en: "Why Astro",
        fr: "Pourquoi Astro",
        es: "Por qué Astro",
        de: "Warum Astro",
        it: "Perché Astro",
        ja: "なぜ Astro なのか",
        ko: "왜 Astro인가",
        zh: "为什么选择 Astro",
        pt: "Por que Astro",
        pl: "Dlaczego Astro",
        hi: "Astro क्यों",
        ar: "لماذا Astro",
        ru: "Почему Astro",
      }),
      default: getDocMetadata("./docs/en/concepts/why-astro.mdx"),
    },
    // Key Guides
    actions: {
      title: t({
        en: "Actions",
        fr: "Actions",
        es: "Acciones",
        de: "Aktionen",
        it: "Azioni",
        ja: "アクション",
        ko: "액션",
        zh: "操作",
        pt: "Ações",
        pl: "Akcje",
        hi: "कार्य",
        ar: "الإجراءات",
        ru: "Действия",
      }),
      default: getDocMetadata("./docs/en/guides/actions.mdx"),
    },
    astroDB: {
      title: t({
        en: "Astro DB",
        fr: "Astro DB",
        es: "Astro DB",
        de: "Astro DB",
        it: "Astro DB",
        ja: "Astro DB",
        ko: "Astro DB",
        zh: "Astro DB",
        pt: "Astro DB",
        pl: "Astro DB",
        hi: "Astro DB",
        ar: "Astro DB",
        ru: "Astro DB",
      }),
      default: getDocMetadata("./docs/en/guides/astro-db.mdx"),
    },
    authentication: {
      title: t({
        en: "Authentication",
        fr: "Authentification",
        es: "Autenticación",
        de: "Authentifizierung",
        it: "Autenticazione",
        ja: "認証",
        ko: "인증",
        zh: "身份验证",
        pt: "Autenticação",
        pl: "Uwierzytelnianie",
        hi: "प्रमाणीकरण",
        ar: "المصادقة",
        ru: "Аутентификация",
      }),
      default: getDocMetadata("./docs/en/guides/authentication.mdx"),
    },
    buildWithAI: {
      title: t({
        en: "Build with AI",
        fr: "Construire avec l'IA",
        es: "Construir con IA",
        de: "Mit KI erstellen",
        it: "Costruire con AI",
        ja: "AI で構築",
        ko: "AI로 구축",
        zh: "使用 AI 构建",
        pt: "Construir com IA",
        pl: "Budowanie z AI",
        hi: "AI के साथ निर्माण",
        ar: "البناء بالذكاء الاصطناعي",
        ru: "Создание с ИИ",
      }),
      default: getDocMetadata("./docs/en/guides/build-with-ai.mdx"),
    },
    clientSideScripts: {
      title: t({
        en: "Client-side Scripts",
        fr: "Scripts côté client",
        es: "Scripts del lado del cliente",
        de: "Client-seitige Skripte",
        it: "Script lato client",
        ja: "クライアントサイドスクリプト",
        ko: "클라이언트 사이드 스크립트",
        zh: "客户端脚本",
        pt: "Scripts do lado do cliente",
        pl: "Skrypty po stronie klienta",
        hi: "क्लाइंट-साइड स्क्रिप्ट",
        ar: "نصوص جانب العميل",
        ru: "Клиентские скрипты",
      }),
      default: getDocMetadata("./docs/en/guides/client-side-scripts.mdx"),
    },
  },
} satisfies Dictionary;

export default docDataContent;
